-- =====================================================================
-- ESQUEMA: Panel de Control de Cotizaciones — Friopacking
-- Generado a partir del archivo "Control de Oportunidades —Friopacking.html"
-- Ejecutar en Supabase: Dashboard -> SQL Editor -> New query -> pegar y correr.
-- =====================================================================

-- Extensión necesaria si luego se quiere usar gen_random_uuid() (no requerida aquí).
-- create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------
-- Tabla principal: oportunidades
-- ---------------------------------------------------------------------
create table if not exists public.oportunidades (
  "Identificador"            integer generated by default as identity primary key,
  cliente                    text not null,
  proyecto                   text,
  tipo_sistema               text,
  refrigerante               text,
  refrigerante_otro          text,
  importe                    numeric(14,2) default 0,
  margen_comercial           numeric(14,2),
  probabilidad_cierre        smallint check (probabilidad_cierre between 0 and 100),
  mes_cierre                 text,               -- formato 'YYYY-MM' o NULL
  segmento_cliente           text check (segmento_cliente in ('agro','no_agro') or segmento_cliente is null),
  valor_no_frio_oocc         numeric(14,2) default 0,
  valor_no_frio_eemm         numeric(14,2) default 0,
  prioridad                  smallint check (prioridad between 1 and 4),
  etapa                      text not null,
  responsable_actual         text,
  presupuestador             text,
  presupuestador_otro        text,
  requiere_metrados          boolean default false,
  resp_metrados              text,
  resp_metrados_otro         text,
  arquitecto                 text,
  arquitecto_otro            text,
  kam                        text,
  kam_otro                   text,
  f_inicio                   date,               -- legado: fecha de inicio (panel antiguo)
  f_comprometida             date,               -- legado: fecha comprometida (panel antiguo)
  f_entregada                date,               -- legado: fecha real de entrega (panel antiguo)
  proximo_paso               text,
  accion_pendiente_cliente   boolean default false,
  descripcion_pendiente      text,
  estado_operativo           text default 'pendiente_interno' check (estado_operativo in ('pendiente_interno','entregado_cliente')),
  ronda_actual               smallint default 1,
  orden_trabajo              integer default 1 check (orden_trabajo is null or orden_trabajo >= 1), -- manual: secuencia de trabajo (1,2,3…N) de Detalle > Oportunidades. Entero libre, NO una categoría de 1 a 4
  prioridad_tablero          smallint default 3 check (prioridad_tablero is null or prioridad_tablero between 1 and 4), -- manual: 1=Crítico,2=Importante,3=Programado,4=En proceso (tablero de Prioridades, Revisión semanal)
  created_at                 timestamptz not null default now(),
  updated_at                 timestamptz not null default now()
);

comment on table public.oportunidades is 'Oportunidades comerciales del pipeline de cotizaciones (fuente: panel HTML de Friopacking).';

-- Migración para bases ya creadas antes de estos campos — "create table if not exists"
-- no los agrega a una tabla existente, así que se agregan aparte de forma idempotente.
-- Para una base ya en uso conviene correr supabase/05_fix_orden_trabajo.sql, que además
-- rellena los valores iniciales de las filas existentes.
alter table public.oportunidades add column if not exists orden_trabajo integer default 1;
alter table public.oportunidades drop constraint if exists oportunidades_orden_trabajo_check;
alter table public.oportunidades add constraint oportunidades_orden_trabajo_check check (orden_trabajo is null or orden_trabajo >= 1);
alter table public.oportunidades add column if not exists prioridad_tablero smallint default 3;
alter table public.oportunidades drop constraint if exists oportunidades_prioridad_tablero_check;
alter table public.oportunidades add constraint oportunidades_prioridad_tablero_check check (prioridad_tablero is null or prioridad_tablero between 1 and 4);

-- ---------------------------------------------------------------------
-- Tabla hija: entregables (1 oportunidad -> N entregables)
-- ---------------------------------------------------------------------
create table if not exists public.entregables (
  "Identificador"              integer generated by default as identity primary key,
  oportunidad_identificador    integer not null references public.oportunidades ("Identificador") on delete cascade,
  nombre                       text,
  area                         text check (area in ('comercial','arquitectura','presupuestos') or area is null),
  responsable                  text,
  responsable_otro             text,
  etapa                        text,
  prioridad                    smallint check (prioridad between 1 and 4),
  fecha_entrega                date,
  fecha_comprometida_cliente   date,
  fecha_completado             date,
  estado                       text check (estado in ('pendiente','completado') or estado is null),
  proximo_paso                 text,
  observacion                  text,
  ronda                        smallint default 1,
  created_at                   timestamptz not null default now(),
  updated_at                   timestamptz not null default now()
);

comment on table public.entregables is 'Entregables internos asociados a cada oportunidad (hoy sin registros cargados).';

create index if not exists idx_entregables_oportunidad on public.entregables (oportunidad_identificador);

-- ---------------------------------------------------------------------
-- Trigger para mantener updated_at al día en cada UPDATE
-- ---------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_oportunidades_updated_at on public.oportunidades;
create trigger trg_oportunidades_updated_at
  before update on public.oportunidades
  for each row execute function public.set_updated_at();

drop trigger if exists trg_entregables_updated_at on public.entregables;
create trigger trg_entregables_updated_at
  before update on public.entregables
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------
-- Row Level Security — habilitado por defecto en Supabase.
-- Ajusta estas políticas según cómo se autentique la app (ver notas de conexión).
-- Mientras no se agreguen políticas "for select/insert/update", con RLS
-- habilitado y SIN políticas, ningún cliente anon/authenticated podrá leer ni escribir.
-- ---------------------------------------------------------------------
alter table public.oportunidades enable row level security;
alter table public.entregables enable row level security;
